// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwAN9OTDNylHJkAjBYg2Av3Usrkr-JFo',
    appId: '1:640527997537:web:c55431f49b8516442fe820',
    messagingSenderId: '640527997537',
    projectId: 'kinotop-39ab2',
    authDomain: 'kinotop-39ab2.firebaseapp.com',
    storageBucket: 'kinotop-39ab2.firebasestorage.app',
    measurementId: 'G-PMFKNXRFGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0qRigsJqwbNn3L0I3B3saSTCZHRBO8eQ',
    appId: '1:640527997537:android:a3052a2f048dae5b2fe820',
    messagingSenderId: '640527997537',
    projectId: 'kinotop-39ab2',
    storageBucket: 'kinotop-39ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIxztK4UC8hjtJT_Ni27IgqYaGSTBLfU',
    appId: '1:640527997537:ios:c8843ea2b513cd7f2fe820',
    messagingSenderId: '640527997537',
    projectId: 'kinotop-39ab2',
    storageBucket: 'kinotop-39ab2.firebasestorage.app',
    iosBundleId: 'com.example.kinoTop',
  );
}
